CREATE TABLE IF NOT EXISTS parsed_jobs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    source VARCHAR(100) NOT NULL,
    source_color VARCHAR(20),
    source_icon VARCHAR(20),
    job_title VARCHAR(255),
    company_name VARCHAR(255),
    company_rating VARCHAR(20),
    location VARCHAR(255),
    experience_required VARCHAR(100),
    salary_range VARCHAR(100),
    work_mode VARCHAR(50),
    skills TEXT,
    apply_link TEXT,
    job_description LONGTEXT,
    email_message_id BIGINT,
    sender_email VARCHAR(255),
    received_at DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_user_id (user_id),
    INDEX idx_source (source),
    INDEX idx_received_at (received_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
