-- Add new columns to companies table
ALTER TABLE companies
  ADD COLUMN IF NOT EXISTS logo VARCHAR(20),
  ADD COLUMN IF NOT EXISTS color VARCHAR(20),
  ADD COLUMN IF NOT EXISTS size VARCHAR(50),
  ADD COLUMN IF NOT EXISTS founded VARCHAR(10),
  ADD COLUMN IF NOT EXISTS rating VARCHAR(10),
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS tech_stack TEXT,
  ADD COLUMN IF NOT EXISTS interview_tips TEXT,
  ADD COLUMN IF NOT EXISTS salary_range VARCHAR(100),
  ADD COLUMN IF NOT EXISTS benefits TEXT,
  ADD COLUMN IF NOT EXISTS difficulty VARCHAR(20),
  ADD COLUMN IF NOT EXISTS work_culture VARCHAR(30);

-- Clear existing and insert rich data
DELETE FROM companies;

INSERT INTO companies (name, industry, location, website, logo, color, size, founded, rating, description, hiring_strategy, interview_process, required_skills, tech_stack, interview_tips, salary_range, benefits, difficulty, work_culture) VALUES

('Google', 'Technology', 'Mountain View, CA / Bangalore, India', 'https://google.com', '🔵', '#4285F4', '100K+ employees', '1998', '4.4',
 'Google is the world''s largest search engine and a leader in AI, cloud computing, and advertising technology.',
 'Google hires for "Googleyness" — a mix of intellectual humility, comfort with ambiguity, and collaborative spirit. They use structured interviews with trained interviewers and focus heavily on problem-solving ability over domain knowledge.',
 '["Resume Screen","Phone Screen (45 min)","Technical Phone Interview x2","Onsite: 4-5 rounds (Coding + System Design + Behavioral)","Hiring Committee Review","Team Matching"]',
 'Data Structures, Algorithms, System Design, Problem Solving, Communication, Leadership',
 'Python, Java, C++, Go, Kubernetes, TensorFlow, BigQuery, Spanner, Borg',
 '["Practice LeetCode Hard problems — Google loves graph, DP, and string problems","System design is critical for L4+: know distributed systems deeply","Use STAR method for behavioral questions","Think out loud — interviewers want to see your thought process","Ask clarifying questions before coding","Google values clean, readable code over clever hacks"]',
 '₹25L – ₹80L (India) | $150K – $350K (US)', 'Free meals, Health insurance, 20% time, Stock options (RSUs), Gym, Parental leave', 'HARD', 'Hybrid'),

('Microsoft', 'Technology', 'Redmond, WA / Hyderabad, India', 'https://microsoft.com', '🟦', '#00A4EF', '200K+ employees', '1975', '4.3',
 'Microsoft is a global technology leader known for Windows, Azure, Office 365, and GitHub. Under Satya Nadella, it has transformed into a cloud-first company.',
 'Microsoft focuses on "growth mindset" — they want candidates who learn from failure and collaborate. They value both technical depth and the ability to work across teams. Diversity and inclusion are core hiring values.',
 '["Resume Screen","Recruiter Call","Technical Phone Screen","Virtual Onsite: 4-5 rounds (Coding + Design + Behavioral)","As-Appropriate Interview (optional)","Offer"]',
 'Data Structures, Algorithms, System Design, .NET/Azure, Problem Solving, Collaboration',
 'C#, TypeScript, Python, Azure, .NET, React, Kubernetes, SQL Server, Power BI',
 '["Microsoft loves behavioral questions — prepare 10+ STAR stories","System design: focus on Azure services and scalability","Coding: medium-hard LeetCode, focus on arrays, trees, graphs","Show growth mindset — talk about what you learned from failures","Research the team you''re interviewing for","Be collaborative — they value teamwork over individual brilliance"]',
 '₹20L – ₹60L (India) | $130K – $300K (US)', 'Health insurance, Stock (RSUs), 401k, Parental leave, Learning budget, Gym', 'HARD', 'Hybrid'),

('Amazon', 'E-commerce / Cloud', 'Seattle, WA / Hyderabad, India', 'https://amazon.com', '🟠', '#FF9900', '1.5M+ employees', '1994', '3.9',
 'Amazon is the world''s largest e-commerce company and cloud provider (AWS). Known for its customer-obsessed culture and 16 Leadership Principles.',
 'Amazon''s entire hiring process revolves around 16 Leadership Principles (LPs). Every interview question maps to an LP. They use the "Bar Raiser" system — a senior employee who ensures every hire raises the bar.',
 '["Online Assessment (2 coding problems + work simulation)","Phone Screen with LP questions","Virtual Onsite: 4-5 rounds (Coding + System Design + LP deep dives)","Bar Raiser round","Debrief and Offer"]',
 'Data Structures, Algorithms, System Design, Leadership Principles, Distributed Systems',
 'Java, Python, AWS (EC2, S3, Lambda, DynamoDB, SQS), React, Kotlin, Rust',
 '["Memorize all 16 Leadership Principles — every question maps to one","Prepare 2-3 STAR stories per LP","System design: focus on AWS services, scalability, fault tolerance","Coding: medium LeetCode, focus on arrays, strings, trees","The Bar Raiser will push back — stay calm and defend your reasoning","Customer Obsession is the most important LP — mention it often"]',
 '₹18L – ₹55L (India) | $120K – $280K (US)', 'Sign-on bonus, RSUs, Health insurance, 401k, Employee discount', 'HARD', 'In-office'),

('Flipkart', 'E-commerce', 'Bangalore, India', 'https://flipkart.com', '🟡', '#F7C600', '30K+ employees', '2007', '4.0',
 'Flipkart is India''s largest e-commerce platform, owned by Walmart. It''s a top destination for tech talent in India with strong engineering culture.',
 'Flipkart looks for strong problem-solving skills and the ability to work at scale. They value candidates who understand Indian market dynamics and can build for scale. Culture fit and ownership mindset are key.',
 '["Online Coding Test","Technical Phone Screen","F2F/Virtual: 3-4 rounds (DSA + LLD + HLD + Hiring Manager)","HR Round"]',
 'Data Structures, Algorithms, Low Level Design, High Level Design, Java/Python, Databases',
 'Java, Kotlin, Python, React, MySQL, Cassandra, Kafka, Spark, Kubernetes',
 '["Focus on Low Level Design (LLD) — Flipkart loves OOP design problems","High Level Design: know microservices, caching, message queues","DSA: medium-hard problems, focus on graphs and DP","Prepare for scale — think millions of users, thousands of TPS","Show ownership — they want people who take end-to-end responsibility","Know Flipkart''s products and tech challenges"]',
 '₹15L – ₹50L', 'Health insurance, Stock options, Flexible work, Learning budget, Meals', 'HARD', 'Hybrid'),

('Infosys', 'IT Services', 'Bangalore, India', 'https://infosys.com', '🔷', '#007CC3', '300K+ employees', '1981', '3.8',
 'Infosys is one of India''s largest IT services companies, serving clients globally in banking, retail, manufacturing, and more.',
 'Infosys hires at scale through campus recruitment and lateral hiring. They value communication skills, adaptability, and willingness to learn. Technical depth is less critical than attitude and trainability for freshers.',
 '["Online Test (Aptitude + Coding + English)","Technical Interview (DSA basics + project discussion)","HR Interview"]',
 'Java, Python, SQL, Communication, Problem Solving, Teamwork',
 'Java, Python, .NET, SQL, Angular, React, AWS, Azure, Selenium',
 '["Aptitude test is critical — practice quantitative and logical reasoning","Basic DSA is enough — focus on arrays, strings, sorting","Prepare to discuss your projects in detail","Communication skills matter as much as technical skills","Research Infosys'' services and recent news","Show willingness to relocate and work in different domains"]',
 '₹3.5L – ₹20L', 'Health insurance, PF, Gratuity, Learning platform (Lex), Referral bonus', 'EASY', 'In-office'),

('TCS', 'IT Services', 'Mumbai, India', 'https://tcs.com', '🔵', '#0033A0', '600K+ employees', '1968', '3.7',
 'TCS (Tata Consultancy Services) is India''s largest IT company and one of the world''s top IT services firms by market cap.',
 'TCS hires hundreds of thousands of freshers annually through TCS NQT (National Qualifier Test). They value attitude, learning agility, and communication. For experienced roles, domain expertise matters.',
 '["TCS NQT (Online Test: Aptitude + Coding + English)","Technical Interview","Managerial Interview","HR Interview"]',
 'Java, Python, SQL, Communication, Aptitude, Domain Knowledge',
 'Java, Python, .NET, SQL, Angular, React, AWS, Azure, Mainframe, SAP',
 '["TCS NQT is the gateway — practice aptitude, verbal, and coding sections","Basic programming in Java or Python is sufficient for freshers","Prepare for HR questions about relocation and work culture","Research TCS'' recent projects and clients","Show enthusiasm for learning new technologies","For experienced roles, highlight domain expertise and certifications"]',
 '₹3.36L – ₹15L', 'Health insurance, PF, Gratuity, TCS Learning Platform, Employee discounts', 'EASY', 'In-office'),

('Wipro', 'IT Services', 'Bangalore, India', 'https://wipro.com', '🟢', '#341C5C', '250K+ employees', '1945', '3.7',
 'Wipro is a leading global IT, consulting, and business process services company headquartered in Bangalore.',
 'Wipro hires through WILP (Wipro Integrated Learning Program) for freshers and lateral hiring for experienced. They value technical skills, communication, and adaptability.',
 '["Online Test (Aptitude + Technical + Coding)","Technical Interview","HR Interview"]',
 'Java, Python, SQL, Communication, Problem Solving',
 'Java, Python, .NET, SQL, React, Angular, AWS, Azure, Salesforce',
 '["Focus on aptitude and verbal sections in the online test","Basic Java/Python programming is sufficient","Prepare for situational HR questions","Research Wipro''s recent acquisitions and focus areas","Show flexibility and willingness to work in different technologies","Certifications in AWS/Azure are a plus"]',
 '₹3.5L – ₹18L', 'Health insurance, PF, Gratuity, Learning platform, Referral bonus', 'EASY', 'In-office'),

('Swiggy', 'Food Tech', 'Bangalore, India', 'https://swiggy.com', '🟠', '#FC8019', '5K+ employees', '2014', '4.1',
 'Swiggy is India''s leading food delivery and quick commerce platform, known for its engineering excellence and fast-paced culture.',
 'Swiggy looks for strong problem-solvers who can build for scale and speed. They value ownership, bias for action, and the ability to work in ambiguity. Strong DSA and system design skills are essential.',
 '["Online Coding Test","Technical Phone Screen","Virtual Onsite: 3-4 rounds (DSA + LLD + HLD + Culture Fit)","HR Round"]',
 'Data Structures, Algorithms, System Design, Java/Python/Go, Databases, Distributed Systems',
 'Java, Go, Python, React, MySQL, Redis, Kafka, Kubernetes, AWS',
 '["Strong DSA is non-negotiable — practice medium-hard LeetCode","System design: focus on real-time systems, location tracking, surge pricing","LLD: design food ordering system, delivery tracking","Show bias for action — they love people who ship fast","Understand Swiggy''s business model and tech challenges","Prepare for culture fit questions about handling ambiguity"]',
 '₹15L – ₹45L', 'Health insurance, Stock options, Free meals, Flexible work, Learning budget', 'HARD', 'Hybrid'),

('Zomato', 'Food Tech', 'Gurugram, India', 'https://zomato.com', '🔴', '#E23744', '5K+ employees', '2008', '4.0',
 'Zomato is India''s leading food delivery platform and restaurant discovery service, expanding into quick commerce with Blinkit.',
 'Zomato values strong engineering fundamentals and the ability to build at scale. They look for people who are passionate about solving real-world problems and can work in a fast-paced startup environment.',
 '["Online Coding Test","Technical Phone Screen","Virtual Onsite: 3-4 rounds (DSA + System Design + Behavioral)","HR Round"]',
 'Data Structures, Algorithms, System Design, Backend Development, Databases',
 'Java, Python, Go, React, MySQL, Redis, Kafka, Elasticsearch, AWS',
 '["Focus on scalability in system design — Zomato handles millions of orders","DSA: medium-hard problems, focus on graphs and dynamic programming","Prepare for questions about real-time systems and geolocation","Show passion for the product — use Zomato and understand its features","Behavioral: show examples of working under pressure","Know Blinkit''s quick commerce model"]',
 '₹12L – ₹40L', 'Health insurance, Stock options, Free meals, Flexible work', 'HARD', 'Hybrid'),

('Razorpay', 'Fintech', 'Bangalore, India', 'https://razorpay.com', '🔵', '#2D9CDB', '3K+ employees', '2014', '4.3',
 'Razorpay is India''s leading payment gateway and fintech platform, processing billions of dollars in transactions annually.',
 'Razorpay looks for engineers who understand financial systems, security, and high-reliability systems. They value strong fundamentals, ownership, and the ability to build mission-critical systems.',
 '["Online Coding Test","Technical Phone Screen","Virtual Onsite: 3-4 rounds (DSA + System Design + Behavioral)","HR Round"]',
 'Data Structures, Algorithms, System Design, Security, Distributed Systems, Databases',
 'Java, Go, Python, React, MySQL, Redis, Kafka, AWS, Kubernetes',
 '["Understand payment systems — NEFT, IMPS, UPI, card networks","System design: focus on reliability, consistency, and security","DSA: medium-hard problems","Show understanding of financial regulations and compliance","Prepare for questions about handling failures in payment systems","Security knowledge is a big plus"]',
 '₹15L – ₹50L', 'Health insurance, Stock options, Flexible work, Learning budget', 'HARD', 'Hybrid'),

('CRED', 'Fintech', 'Bangalore, India', 'https://cred.club', '⚫', '#1A1A2E', '1K+ employees', '2018', '4.2',
 'CRED is a premium fintech platform for credit card bill payments and financial services, known for its design-first culture and high engineering standards.',
 'CRED has extremely high hiring standards — they hire less than 1% of applicants. They look for exceptional engineers who care deeply about craft, design, and user experience. Strong fundamentals and attention to detail are critical.',
 '["Resume Screen (very selective)","Technical Phone Screen","Virtual Onsite: 4-5 rounds (DSA + System Design + Architecture + Culture)","Founder/CTO Round for senior roles"]',
 'Data Structures, Algorithms, System Design, Architecture, Attention to Detail',
 'Kotlin, Swift, Go, Python, React, PostgreSQL, Redis, Kafka, AWS',
 '["CRED is extremely selective — your resume must stand out","System design: focus on elegant, scalable architectures","DSA: hard LeetCode problems","Show passion for craft and design — CRED values aesthetics","Prepare for deep architecture discussions","Research CRED''s products thoroughly — they expect you to be a user","Culture fit is critical — show alignment with their values"]',
 '₹20L – ₹60L', 'Health insurance, Stock options, Premium office, Learning budget, Flexible work', 'HARD', 'Hybrid'),

('PhonePe', 'Fintech', 'Bangalore, India', 'https://phonepe.com', '🟣', '#5F259F', '4K+ employees', '2015', '4.1',
 'PhonePe is India''s largest digital payments platform with 500M+ registered users, backed by Walmart.',
 'PhonePe looks for engineers who can build reliable, scalable payment systems. They value strong fundamentals, ownership, and the ability to work in a high-growth environment.',
 '["Online Coding Test","Technical Phone Screen","Virtual Onsite: 3-4 rounds (DSA + System Design + Behavioral)","HR Round"]',
 'Data Structures, Algorithms, System Design, Java/Go, Distributed Systems',
 'Java, Go, Python, React, MySQL, Redis, Kafka, AWS, Kubernetes',
 '["Understand UPI and digital payment systems deeply","System design: focus on high availability and consistency","DSA: medium-hard problems","Show understanding of financial regulations","Prepare for questions about handling payment failures","Strong Java skills are preferred"]',
 '₹15L – ₹45L', 'Health insurance, Stock options, Flexible work, Learning budget', 'HARD', 'Hybrid'),

('Meesho', 'E-commerce', 'Bangalore, India', 'https://meesho.com', '🟣', '#9B59B6', '3K+ employees', '2015', '4.0',
 'Meesho is India''s fastest-growing social commerce platform, enabling millions of small businesses to sell online.',
 'Meesho values strong problem-solving skills and the ability to build for Bharat (tier 2/3 cities). They look for people who understand the unique challenges of building for low-bandwidth, low-cost devices.',
 '["Online Coding Test","Technical Phone Screen","Virtual Onsite: 3-4 rounds (DSA + System Design + Behavioral)","HR Round"]',
 'Data Structures, Algorithms, System Design, Backend Development, Mobile Development',
 'Java, Kotlin, Python, React Native, MySQL, Redis, Kafka, AWS',
 '["Understand Meesho''s unique market — social commerce for Bharat","System design: focus on low-bandwidth optimization","DSA: medium problems","Show empathy for users in tier 2/3 cities","Prepare for questions about building for scale with cost constraints","Mobile development experience is a plus"]',
 '₹12L – ₹35L', 'Health insurance, Stock options, Flexible work, Learning budget', 'MEDIUM', 'Hybrid'),

('Ola', 'Mobility / EV', 'Bangalore, India', 'https://olacabs.com', '🟡', '#FFC72C', '5K+ employees', '2010', '3.8',
 'Ola is India''s largest ride-hailing platform, now expanding into electric vehicles with Ola Electric.',
 'Ola looks for engineers who can build real-time systems at scale. They value strong fundamentals and the ability to work in a fast-paced environment with frequent pivots.',
 '["Online Coding Test","Technical Phone Screen","Virtual Onsite: 3-4 rounds (DSA + System Design + Behavioral)","HR Round"]',
 'Data Structures, Algorithms, System Design, Real-time Systems, Geolocation',
 'Java, Go, Python, React, MySQL, Redis, Kafka, Elasticsearch, AWS',
 '["Focus on real-time systems in system design — ride matching, surge pricing","Geolocation algorithms are important","DSA: medium-hard problems","Show adaptability — Ola pivots frequently","Prepare for questions about handling driver-rider matching at scale","EV knowledge is a plus for Ola Electric roles"]',
 '₹12L – ₹40L', 'Health insurance, Stock options, Cab credits, Flexible work', 'MEDIUM', 'Hybrid'),

('Paytm', 'Fintech', 'Noida, India', 'https://paytm.com', '🔵', '#00BAF2', '10K+ employees', '2010', '3.6',
 'Paytm is India''s pioneer in digital payments and financial services, offering payments, banking, insurance, and wealth management.',
 'Paytm looks for engineers with strong fundamentals and experience in high-scale systems. They value ownership and the ability to work across the full stack.',
 '["Online Coding Test","Technical Phone Screen","Virtual Onsite: 3-4 rounds (DSA + System Design + Behavioral)","HR Round"]',
 'Data Structures, Algorithms, System Design, Java/Python, Databases, Payment Systems',
 'Java, Python, React, MySQL, Redis, Kafka, AWS, Kubernetes',
 '["Understand digital payment systems and UPI","System design: focus on high-volume transaction processing","DSA: medium problems","Show understanding of financial regulations","Prepare for full-stack questions","Payment security knowledge is important"]',
 '₹10L – ₹35L', 'Health insurance, Stock options, Flexible work', 'MEDIUM', 'In-office'),

('Atlassian', 'Technology', 'Sydney, Australia / Bangalore, India', 'https://atlassian.com', '🔵', '#0052CC', '10K+ employees', '2002', '4.5',
 'Atlassian makes Jira, Confluence, Trello, and Bitbucket — tools used by millions of teams worldwide. Known for its unique "no-manager" culture.',
 'Atlassian has a unique hiring process with no traditional onsite. They focus on values alignment (Open company, no bullshit; Build with heart and balance; Don''t #@!% the customer; Play, as a team; Be the change you seek).',
 '["Resume Screen","Recruiter Call","Technical Assessment (take-home)","Values Interview","Technical Interview x2","Offer"]',
 'Data Structures, Algorithms, System Design, Collaboration Tools, Values Alignment',
 'Java, Python, TypeScript, React, AWS, Kubernetes, PostgreSQL, Kafka',
 '["Research Atlassian''s 5 values deeply — they''re central to hiring","Take-home assessment: focus on code quality and documentation","System design: focus on collaboration tools and distributed systems","Show genuine passion for developer tools","Behavioral: use STAR with emphasis on teamwork and transparency","No traditional onsite — be comfortable with async communication"]',
 '₹20L – ₹60L (India) | $140K – $320K (US)', 'Remote-first, Health insurance, Stock options, Learning budget, Team trips', 'HARD', 'Remote'),

('Uber', 'Mobility / Technology', 'San Francisco, CA / Bangalore, India', 'https://uber.com', '⚫', '#000000', '30K+ employees', '2009', '4.1',
 'Uber is the world''s largest ride-hailing platform, also operating in food delivery (Uber Eats) and freight.',
 'Uber looks for engineers who can build reliable, scalable systems for real-time operations. They value strong fundamentals, data-driven thinking, and the ability to work in a global, distributed team.',
 '["Online Coding Test","Technical Phone Screen","Virtual Onsite: 4-5 rounds (Coding + System Design + Behavioral + Hiring Manager)","Offer"]',
 'Data Structures, Algorithms, System Design, Distributed Systems, Real-time Systems',
 'Go, Java, Python, React, MySQL, Cassandra, Kafka, Kubernetes, AWS',
 '["System design is critical — know real-time matching, surge pricing, maps","DSA: medium-hard LeetCode, focus on graphs and dynamic programming","Uber loves Go — learn it if you haven''t","Prepare for questions about reliability and fault tolerance","Show data-driven thinking — Uber is very metrics-focused","Behavioral: show examples of working in ambiguity"]',
 '₹20L – ₹60L (India) | $150K – $350K (US)', 'Health insurance, Stock options, Uber credits, Flexible work, Learning budget', 'HARD', 'Hybrid');
